import {BOSS_ARENA_PLACEMENT, DESERT_BOSS_ARENA_PLACEMENT, ICE_BOSS_ARENA_PLACEMENT} from './chunkArenaLayouts.js';

/**
 * Chunk landscape profiles — seeded “micro-biomes” inside each world biome.
 * Each chunk rolls one profile (weighted) and uses its layout + pools for props,
 * interactables, and mob packs (Minecraft-style regional identity).
 */

/** @typedef {'clusters'|'sparse'|'clearing'|'perimeter_ring'|'wet_corner'|'stone_field'|'ancient_grove'|'boss_arena'|'lumberyard'|'forest_mine'|'desert_quarry'|'desert_scrap_yard'|'ice_crystal_mine'|'ice_frozen_depot'|'lava_magma_quarry'|'lava_ash_depot'} ChunkLayout */

/**
 * @typedef {object} ChunkLandscapeProfile
 * @property {string} id
 * @property {string} label
 * @property {number} weight
 * @property {number} density
 * @property {number} [basePropCount]
 * @property {ChunkLayout} layout
 * @property {{ min: number, max: number }} [clusterCount]
 * @property {{ min: number, max: number }} [clusterRadius]
 * @property {Array<{ type: string, weight: number }>} props
 * @property {Record<string, number>} [spacingScale]
 * @property {Record<string, number>} [variantBias]
 * @property {Record<string, number>} [interactableScale]
 * @property {number} [mobPackBonus]
 * @property {number} [mobPackCountMul]
 * @property {boolean} [spawnBoss]
 * @property {string} [bossType]
 * @property {number} [bossScale]
 * @property {import('./chunkArenaLayouts.js').ArenaPlacement[]} [arenaPlacements]
 * @property {boolean} [skipMobPacks]
 * @property {boolean} [skipInteractables]
 * @property {'mob_pack'|'dense_pack'} [forceChunkType]
 * @property {Record<string, number>} [interactableMaxMul]
 * @property {Array<{ radiusMin: number, radiusMax: number, count: number }>} [lakes]
 */

/** @type {Record<string, ChunkLandscapeProfile[]>} */
export const BIOME_CHUNK_PROFILES = {
    forest: [
        {
            id: 'lumberyard',
            label: 'Lumberyard',
            weight: 12,
            density: 1.55,
            basePropCount: 108,
            layout: 'lumberyard',
            forceChunkType: 'dense_pack',
            props: [
                { type: 'TREE', weight: 58 },
                { type: 'BUSH', weight: 27 },
                { type: 'STONE', weight: 15 },
            ],
            spacingScale: { TREE: 0.32, BUSH: 0.34, STONE: 0.55 },
            interactableScale: { wood: 1, container: 1, herb: 0.05, metal: 0.05, chest: 0.25 },
            interactableMaxMul: { wood: 3, container: 2.5 },
            mobPackBonus: 0.58,
            mobPackCountMul: 1.12,
            lakes: [],
        },
        {
            id: 'forest_mine',
            label: 'Forest Mine',
            weight: 12,
            density: 1.4,
            basePropCount: 98,
            layout: 'forest_mine',
            forceChunkType: 'dense_pack',
            props: [
                { type: 'STONE', weight: 62 },
                { type: 'TREE', weight: 23 },
                { type: 'BUSH', weight: 15 },
            ],
            spacingScale: { STONE: 0.28, TREE: 0.48, BUSH: 0.45 },
            interactableScale: { metal: 1, wood: 0.05, herb: 0.05, container: 0.2, chest: 0.2 },
            interactableMaxMul: { metal: 3.5 },
            mobPackBonus: 0.55,
            mobPackCountMul: 1.1,
            lakes: [],
        },
        {
            id: 'dense_forest',
            label: 'Dense Forest',
            weight: 18,
            density: 1.85,
            basePropCount: 88,
            layout: 'clusters',
            clusterCount: { min: 7, max: 12 },
            clusterRadius: { min: 90, max: 170 },
            props: [
                { type: 'TREE', weight: 52 },
                { type: 'BUSH', weight: 33 },
                { type: 'STONE', weight: 15 },
            ],
            spacingScale: { TREE: 0.28, BUSH: 0.32, STONE: 0.22 },
            interactableScale: { wood: 1.2, herb: 0.9, metal: 0.7, container: 0.8 },
            mobPackBonus: 0.22,
            mobPackCountMul: 1.25,
            lakes: [],
        },
        {
            id: 'light_forest',
            label: 'Light Forest',
            weight: 14,
            density: 1.35,
            basePropCount: 52,
            layout: 'sparse',
            props: [
                { type: 'TREE', weight: 42 },
                { type: 'BUSH', weight: 48 },
                { type: 'STONE', weight: 10 },
            ],
            spacingScale: { TREE: 0.52, BUSH: 0.48, STONE: 0.75 },
            interactableScale: { wood: 0.7, herb: 1.1, chest: 0.9 },
            mobPackBonus: 0.16,
            mobPackCountMul: 1.08,
            lakes: [{ radiusMin: 180, radiusMax: 340, count: 1 }],
        },
        {
            id: 'ancient_grove',
            label: 'Ancient Grove',
            weight: 12,
            density: 1.45,
            basePropCount: 58,
            layout: 'ancient_grove',
            clusterCount: { min: 1, max: 2 },
            clusterRadius: { min: 140, max: 220 },
            props: [
                { type: 'TREE', weight: 70 },
                { type: 'BUSH', weight: 18 },
                { type: 'STONE', weight: 12 },
            ],
            spacingScale: { TREE: 0.38, BUSH: 0.42, STONE: 0.35 },
            variantBias: { tree2: 2.5, tree3: 2.5, tree1: 0.6 },
            interactableScale: { herb: 1.35, wood: 1.1, chest: 1.2, metal: 0.5 },
            mobPackBonus: 0.18,
            mobPackCountMul: 1.1,
            lakes: [],
        },
        {
            id: 'rocky_forest',
            label: 'Rocky Forest',
            weight: 16,
            density: 1.35,
            basePropCount: 48,
            layout: 'stone_field',
            clusterCount: { min: 2, max: 4 },
            clusterRadius: { min: 60, max: 110 },
            props: [
                { type: 'STONE', weight: 48 },
                { type: 'TREE', weight: 28 },
                { type: 'BUSH', weight: 24 },
            ],
            spacingScale: { STONE: 0.28, TREE: 0.5, BUSH: 0.45 },
            interactableScale: { metal: 1.45, wood: 0.6, herb: 0.7 },
            mobPackBonus: 0.2,
            mobPackCountMul: 1.08,
            lakes: [{ radiusMin: 160, radiusMax: 300, count: 1 }],
        },
        {
            id: 'swamp_forest',
            label: 'Swamp Forest',
            weight: 14,
            density: 1.5,
            basePropCount: 62,
            layout: 'wet_corner',
            props: [
                { type: 'BUSH', weight: 38 },
                { type: 'TREE', weight: 32 },
                { type: 'STONE', weight: 30 },
            ],
            spacingScale: { TREE: 0.38, BUSH: 0.3, STONE: 0.42 },
            interactableScale: { herb: 1.5, wood: 1.25, container: 1.2, metal: 0.4 },
            mobPackBonus: 0.24,
            mobPackCountMul: 1.18,
            lakes: [],
        },
        {
            id: 'tree_grove_boss',
            label: 'Tree Grove Boss',
            weight: 2,
            density: 0,
            basePropCount: 0,
            layout: 'boss_arena',
            spawnBoss: true,
            bossType: 'forest',
            bossScale: 1.2,
            arenaPlacements: BOSS_ARENA_PLACEMENT,
            skipMobPacks: true,
            skipInteractables: true,
            props: [],
        },
        {
            id: 'mushroom_glade',
            label: 'Mushroom Glade',
            weight: 12,
            density: 1.4,
            basePropCount: 56,
            layout: 'perimeter_ring',
            props: [
                { type: 'TREE', weight: 38 },
                { type: 'BUSH', weight: 52 },
                { type: 'STONE', weight: 10 },
            ],
            spacingScale: { TREE: 0.42, BUSH: 0.34, STONE: 0.55 },
            variantBias: { bush2: 1.8, bush3: 1.8, herb_green: 1 },
            interactableScale: { herb: 1.6, wood: 0.5, chest: 0.85, container: 0.9 },
            mobPackBonus: 0.14,
            mobPackCountMul: 1.05,
            lakes: [{ radiusMin: 200, radiusMax: 320, count: 1 }],
        },
    ],

    desert: [
        {
            id: 'desert_quarry',
            label: 'Sandstone Quarry',
            weight: 12,
            density: 1.1,
            basePropCount: 46,
            layout: 'desert_quarry',
            forceChunkType: 'dense_pack',
            props: [
                { type: 'CACTUS', weight: 42 },
                { type: 'DESERT_TREE', weight: 38 },
                { type: 'DESERT_BUSH', weight: 20 },
            ],
            spacingScale: { CACTUS: 0.36, DESERT_TREE: 0.42, DESERT_BUSH: 0.75 },
            interactableScale: { metal: 1, container: 0.25, chest: 0.3, herb: 0.15, wood: 0.05 },
            interactableMaxMul: { metal: 3.5 },
            mobPackBonus: 0.5,
            mobPackCountMul: 2.4,
        },
        {
            id: 'desert_scrap_yard',
            label: 'Scrap Yard',
            weight: 11,
            density: 1.05,
            basePropCount: 40,
            layout: 'desert_scrap_yard',
            forceChunkType: 'dense_pack',
            props: [
                { type: 'CACTUS', weight: 45 },
                { type: 'DESERT_TREE', weight: 25 },
                { type: 'DESERT_BUSH', weight: 30 },
            ],
            spacingScale: { CACTUS: 0.5, DESERT_TREE: 0.48, DESERT_BUSH: 0.55 },
            interactableScale: { container: 1, wood: 0.35, metal: 0.4, chest: 0.35, herb: 0.1 },
            interactableMaxMul: { container: 2.5, wood: 2 },
            mobPackBonus: 0.48,
            mobPackCountMul: 2.3,
        },
        {
            id: 'rocky_badlands',
            label: 'Rocky Badlands',
            weight: 14,
            density: 0.9,
            basePropCount: 22,
            layout: 'stone_field',
            clusterCount: { min: 2, max: 4 },
            clusterRadius: { min: 65, max: 120 },
            props: [
                { type: 'CACTUS', weight: 55 },
                { type: 'DESERT_TREE', weight: 30 },
                { type: 'DESERT_BUSH', weight: 15 },
            ],
            spacingScale: { CACTUS: 0.34, DESERT_TREE: 0.4, DESERT_BUSH: 0.7 },
            interactableScale: { metal: 1.5, chest: 1.15, container: 0.7 },
            mobPackBonus: 0.12,
            mobPackCountMul: 1.15,
        },
        {
            id: 'dune_field',
            label: 'Dune Field',
            weight: 13,
            density: 0.48,
            basePropCount: 10,
            layout: 'sparse',
            props: [
                { type: 'DESERT_TREE', weight: 35 },
                { type: 'CACTUS', weight: 40 },
                { type: 'DESERT_BUSH', weight: 25 },
            ],
            spacingScale: { DESERT_TREE: 0.75, CACTUS: 0.88, DESERT_BUSH: 1.05 },
            interactableScale: { metal: 1.25, chest: 0.9, container: 0.5 },
            mobPackBonus: 0.05,
        },
        {
            id: 'sand_ridge',
            label: 'Sand Ridge',
            weight: 11,
            density: 0.88,
            basePropCount: 20,
            layout: 'perimeter_ring',
            props: [
                { type: 'CACTUS', weight: 50 },
                { type: 'DESERT_TREE', weight: 28 },
                { type: 'DESERT_BUSH', weight: 22 },
            ],
            spacingScale: { CACTUS: 0.68, DESERT_TREE: 0.62, DESERT_BUSH: 0.7 },
            interactableScale: { metal: 1.2, container: 0.85, chest: 0.75 },
            mobPackBonus: 0.08,
        },
        {
            id: 'oasis_edge',
            label: 'Oasis Edge',
            weight: 10,
            density: 0.72,
            basePropCount: 14,
            layout: 'wet_corner',
            props: [
                { type: 'DESERT_TREE', weight: 38 },
                { type: 'DESERT_BUSH', weight: 42 },
                { type: 'CACTUS', weight: 20 },
            ],
            spacingScale: { DESERT_TREE: 0.58, DESERT_BUSH: 0.55, CACTUS: 0.72 },
            interactableScale: { herb: 1.45, container: 1.1, metal: 0.9, chest: 0.8 },
            mobPackBonus: 0.1,
        },
        {
            id: 'scorched_stone_clusters',
            label: 'Scorched Stone Clusters',
            weight: 10,
            density: 1.0,
            basePropCount: 18,
            layout: 'clusters',
            clusterCount: { min: 2, max: 4 },
            clusterRadius: { min: 85, max: 150 },
            props: [
                { type: 'CACTUS', weight: 65 },
                { type: 'DESERT_TREE', weight: 25 },
                { type: 'DESERT_BUSH', weight: 10 },
            ],
            spacingScale: { CACTUS: 0.42, DESERT_TREE: 0.45, DESERT_BUSH: 0.65 },
            interactableScale: { metal: 1.35, chest: 1.0 },
            mobPackBonus: 0.11,
            lakes: [{ radiusMin: 180, radiusMax: 340, count: 1 }],
        },
        {
            id: 'sand_titan_arena',
            label: 'Sand Titan Arena',
            weight: 7,
            density: 0,
            basePropCount: 0,
            layout: 'boss_arena',
            spawnBoss: true,
            bossType: 'desert',
            bossScale: 1.2,
            arenaPlacements: DESERT_BOSS_ARENA_PLACEMENT,
            skipMobPacks: true,
            skipInteractables: true,
            props: [],
        },
    ],

    ice: [
        {
            id: 'ice_crystal_mine',
            label: 'Crystal Mine',
            weight: 12,
            density: 1.08,
            basePropCount: 44,
            layout: 'ice_crystal_mine',
            forceChunkType: 'dense_pack',
            props: [{ type: 'SNOW_STONE', weight: 82 }, { type: 'STONE', weight: 18 }],
            spacingScale: { SNOW_STONE: 0.36, STONE: 0.65 },
            interactableScale: { metal: 1, chest: 0.3, herb: 0.35, container: 0.15, wood: 0.05 },
            interactableMaxMul: { metal: 3.6 },
            mobPackBonus: 0.5,
            mobPackCountMul: 2.5,
        },
        {
            id: 'ice_frozen_depot',
            label: 'Frozen Depot',
            weight: 11,
            density: 1.0,
            basePropCount: 38,
            layout: 'ice_frozen_depot',
            forceChunkType: 'dense_pack',
            props: [{ type: 'SNOW_STONE', weight: 60 }, { type: 'SNOW_TREE', weight: 40 }],
            spacingScale: { SNOW_STONE: 0.48, SNOW_TREE: 0.55 },
            interactableScale: { container: 1, wood: 0.5, metal: 0.35, chest: 0.4, herb: 0.25 },
            interactableMaxMul: { container: 2.2, wood: 2 },
            mobPackBonus: 0.48,
            mobPackCountMul: 2.35,
        },
        {
            id: 'ice_spire_field',
            label: 'Ice Spire Field',
            weight: 14,
            density: 0.88,
            basePropCount: 18,
            layout: 'stone_field',
            clusterCount: { min: 2, max: 4 },
            clusterRadius: { min: 75, max: 135 },
            props: [{ type: 'SNOW_STONE', weight: 100 }],
            spacingScale: { SNOW_STONE: 0.36 },
            interactableScale: { metal: 1.4, chest: 1.2, herb: 0.5 },
            mobPackBonus: 0.11,
            lakes: [{ radiusMin: 200, radiusMax: 320, count: 1 }],
        },
        {
            id: 'frozen_expanse',
            label: 'Frozen Expanse',
            weight: 12,
            density: 0.42,
            basePropCount: 8,
            layout: 'sparse',
            props: [{ type: 'SNOW_STONE', weight: 100 }],
            spacingScale: { SNOW_STONE: 0.82 },
            interactableScale: { metal: 1.1, chest: 0.85, herb: 0.4 },
            mobPackBonus: 0.04,
        },
        {
            id: 'glacial_ring',
            label: 'Glacial Ring',
            weight: 11,
            density: 0.85,
            basePropCount: 18,
            layout: 'perimeter_ring',
            props: [{ type: 'SNOW_STONE', weight: 80 }, { type: 'SNOW_TREE', weight: 20 }],
            spacingScale: { SNOW_STONE: 0.65, SNOW_TREE: 0.6 },
            interactableScale: { metal: 1.15, herb: 1.2, chest: 0.8 },
            mobPackBonus: 0.07,
        },
        {
            id: 'frost_corner',
            label: 'Frost Hollow',
            weight: 10,
            density: 0.95,
            basePropCount: 16,
            layout: 'wet_corner',
            props: [{ type: 'SNOW_STONE', weight: 55 }, { type: 'SNOW_TREE', weight: 45 }],
            spacingScale: { SNOW_STONE: 0.52, SNOW_TREE: 0.5 },
            interactableScale: { herb: 1.55, metal: 0.95, chest: 0.85, container: 0.6 },
            mobPackBonus: 0.1,
        },
        {
            id: 'blizzard_clusters',
            label: 'Blizzard Clusters',
            weight: 10,
            density: 0.78,
            basePropCount: 14,
            layout: 'clusters',
            clusterCount: { min: 2, max: 3 },
            clusterRadius: { min: 95, max: 155 },
            props: [{ type: 'SNOW_STONE', weight: 75 }, { type: 'STONE', weight: 25 }],
            spacingScale: { SNOW_STONE: 0.48, STONE: 0.58 },
            interactableScale: { chest: 1.25, metal: 1.15, herb: 0.45 },
            mobPackBonus: 0.09,
        },
        {
            id: 'frost_colossus_arena',
            label: 'Frost Colossus Arena',
            weight: 7,
            density: 0,
            basePropCount: 0,
            layout: 'boss_arena',
            spawnBoss: true,
            bossType: 'ice',
            bossScale: 1.2,
            arenaPlacements: ICE_BOSS_ARENA_PLACEMENT,
            skipMobPacks: true,
            skipInteractables: true,
            props: [],
        },
    ],

    lava: [
        {
            id: 'lava_magma_quarry',
            label: 'Magma Quarry',
            weight: 12,
            density: 1.12,
            basePropCount: 48,
            layout: 'lava_magma_quarry',
            forceChunkType: 'dense_pack',
            props: [{ type: 'LAVA_STONE', weight: 92 }, { type: 'BUSH', weight: 8 }],
            spacingScale: { STONE: 0.32, BUSH: 0.85 },
            interactableScale: { metal: 1, container: 0.2, chest: 0.35, herb: 0.05, wood: 0.05 },
            interactableMaxMul: { metal: 4 },
            mobPackBonus: 0.52,
            mobPackCountMul: 2.6,
        },
        {
            id: 'lava_ash_depot',
            label: 'Ash Depot',
            weight: 11,
            density: 1.02,
            basePropCount: 36,
            layout: 'lava_ash_depot',
            forceChunkType: 'dense_pack',
            props: [{ type: 'LAVA_STONE', weight: 85 }, { type: 'BUSH', weight: 15 }],
            spacingScale: { STONE: 0.44, BUSH: 0.7 },
            interactableScale: { container: 1, metal: 0.55, chest: 0.45, wood: 0.1 },
            interactableMaxMul: { container: 2.4, metal: 2 },
            mobPackBonus: 0.5,
            mobPackCountMul: 2.45,
        },
        {
            id: 'obsidian_ridge',
            label: 'Obsidian Ridge',
            weight: 14,
            density: 1.05,
            basePropCount: 20,
            layout: 'stone_field',
            clusterCount: { min: 2, max: 4 },
            clusterRadius: { min: 60, max: 115 },
            props: [{ type: 'LAVA_STONE', weight: 100 }],
            spacingScale: { STONE: 0.28 },
            interactableScale: { metal: 1.55, chest: 1.2 },
            mobPackBonus: 0.14,
            mobPackCountMul: 1.2,
        },
        {
            id: 'ash_plains',
            label: 'Ash Plains',
            weight: 12,
            density: 0.52,
            basePropCount: 11,
            layout: 'sparse',
            props: [{ type: 'LAVA_STONE', weight: 100 }],
            spacingScale: { STONE: 0.78 },
            interactableScale: { metal: 1.3, chest: 0.9 },
            mobPackBonus: 0.1,
        },
        {
            id: 'ember_ring',
            label: 'Ember Ring',
            weight: 10,
            density: 0.9,
            basePropCount: 18,
            layout: 'perimeter_ring',
            props: [{ type: 'LAVA_STONE', weight: 90 }, { type: 'BUSH', weight: 10 }],
            spacingScale: { STONE: 0.62, BUSH: 0.8 },
            interactableScale: { metal: 1.35, container: 0.75, chest: 0.7 },
            mobPackBonus: 0.09,
        },
        {
            id: 'scorched_canyon',
            label: 'Scorched Canyon',
            weight: 10,
            density: 0.88,
            basePropCount: 15,
            layout: 'clearing',
            props: [{ type: 'LAVA_STONE', weight: 88 }, { type: 'BUSH', weight: 12 }],
            spacingScale: { STONE: 0.42, BUSH: 0.88 },
            interactableScale: { metal: 1.25, container: 0.65, chest: 0.6 },
            mobPackBonus: 0.08,
        },
        {
            id: 'magma_clusters',
            label: 'Magma Clusters',
            weight: 9,
            density: 0.95,
            basePropCount: 17,
            layout: 'clusters',
            clusterCount: { min: 2, max: 4 },
            clusterRadius: { min: 70, max: 125 },
            props: [{ type: 'LAVA_STONE', weight: 100 }],
            spacingScale: { STONE: 0.38 },
            interactableScale: { metal: 1.45, chest: 1.05 },
            mobPackBonus: 0.12,
            mobPackCountMul: 1.15,
        },
    ],
};

/** Fallback when biome has no profiles */
export const DEFAULT_CHUNK_PROFILE = {
    id: 'default',
    label: 'Wilderness',
    weight: 1,
    density: 0.75,
    basePropCount: 18,
    layout: 'sparse',
    props: [
        { type: 'STONE', weight: 40 },
        { type: 'TREE', weight: 35 },
        { type: 'BUSH', weight: 25 },
    ],
    lakes: [],
};
